name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install LaTeX
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: texlive-latex-base texlive-lang-cyrillic texlive-lang-greek texlive-latex-extra texlive-latex-recommended texlive-pictures texlive-plain-generic texlive-science
      
      - name: Rehash LaTeX
        run: sudo texhash

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35

      - name: Render pdfs
        run: |
          for item in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ "$item" != *.tex ]]
            then
              continue
            fi
            INPUT_PATH="${item}"
            OUTPUT_DIRECTORY="${item/sources/renders}"
            OUTPUT_DIRECTORY="${OUTPUT_DIRECTORY%/*}"
            mkdir -p "${{ github.workspace }}/${OUTPUT_DIRECTORY}"
            cd "${{ github.workspace }}/${OUTPUT_DIRECTORY}"
            pdflatex -synctex=1 -interaction=nonstopmode --shell-escape "${{ github.workspace }}/${INPUT_PATH}"
            pdflatex -synctex=1 -interaction=nonstopmode --shell-escape "${{ github.workspace }}/${INPUT_PATH}"
          done

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Upload renders
          file_pattern: '*.pdf'
