name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install LaTeX
        run: sudo apt install texlive-latex-base texlive-lang-cyrillic texlive-lang-greek texlive-latex-extra texlive-latex-recommended texlive-pictures texlive-plain-generic texlive-science

      - name: Render pdfs
        run: bash scripts/render.bash
        shell: bash

      - name: Remove files ignored files
        run: git rm --cached `git ls-files -ic --exclude-from=.gitignore`

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Upload renders'
